version: "3.0"

services:
  liquidsoap:
    build:
      context: liquidsoap
      args:
        gitbranch: master
        version: 1.4.0
        buildnumber: 2065
    image: privyplace/liquidsoap:master-1.4.0-2065
    container_name: liquidsoap
    command: /radio/live.liq
    restart: unless-stopped
    networks:
      - default
    ports:
      - 10000:10000/udp
      - 10001:10001/udp
      - 8500:8500/tcp
    volumes:
     - ./radio:/radio
     - ./hls:/hls

  nginx:
    build:
      context: nginxhls
    image: privyplace/nginxhls:latest
    container_name: nginx
    restart: unless-stopped
    networks:
     - default
    ports:
     - 8080:80/tcp
    volumes:
     - ./hls:/hls

networks:
  default:
