version: "3.0"

services:
  liquidsoap:
    build:
      context: liquidsoap
      args:
        gitbranch: reporting-tools
        version: 1.5.0
        buildnumber: 2444
    image: privyplace/liquidsoap:reporting-tools-1.5.0-2444
    container_name: liquidsoap
    command: /radio/live.liq
    restart: unless-stopped
    networks:
      - default
    ports:
      - 10000:10000/udp
      - 10001:10001/udp
      - 8500:8500/tcp
      - 8081:8081/tcp
      - 9090:9090/tcp
    volumes:
     - ./radio:/radio
     - ./hls:/hls

  nginx:
    build:
      context: nginxhls
    image: privyplace/nginxhls:v1
    container_name: nginx
    restart: unless-stopped
    networks:
     - default
    ports:
     - 8080:80/tcp
    volumes:
     - ./hls:/hls

networks:
  default:
